import { TRUST_PRODUCT_ID } from '../trust/scenarios.js';

/**
 * M12.2 — The pilot sandbox tenant.
 *
 * A dedicated, RLS-isolated business the owner practices against before Meta.
 * It is deliberately UNLIKE the demo factory in one safety-critical way:
 *
 *   IT HAS NO channel_credentials ROW.
 *
 * Inbound tenant identity is resolved ONLY by resolve_tenant('whatsapp',
 * phone_number_id) against channel_credentials. With no credential mapping, a
 * real Meta/360dialog webhook can NEVER route to the sandbox — isolation is a
 * property of the seed data, not a runtime check. The sandbox is reachable only
 * through the owner-authenticated /app/sandbox surface.
 *
 * The product is seeded with TRUST_PRODUCT_ID so the M12.1 golden scenarios
 * replay faithfully against the real tenant (same id → real quote from real
 * pricing). Clients/conversations are created lazily by ensureConversation.
 */

export const SANDBOX_BUSINESS_ID = '5a4d0000-0000-4000-8000-0000000000b1';

const esc = (s: string): string => s.replace(/'/g, "''");

/** Idempotent seed — every insert is `on conflict do nothing`; safe to re-run. */
export function sandboxSeedSql(): string {
  const B = SANDBOX_BUSINESS_ID;
  const P = TRUST_PRODUCT_ID as string;
  const out: string[] = [
    `-- M12.2 sandbox tenant seed (generated by src/demo/sandbox.ts — do not hand-edit)`,
    `-- NOTE: intentionally NO channel_credentials row — the sandbox is unroutable from any provider.`,
    `insert into businesses (id, name, timezone, default_language, engine) values`,
    `  ('${B}', '${esc('Practice sandbox')}', 'Asia/Shanghai', 'en', 'service')`,
    `  on conflict (id) do nothing;`,

    // One product, priced so the floor is meaningful — matches the trust fixtures.
    `insert into products (id, business_id, sku, name, name_zh, category, unit, moq, lead_time_days, price_usd_per_unit) values`,
    `  ('${P}', '${B}', 'BAG-NW-001', '${esc('Non-woven shopping bag')}', '${esc('无纺布购物袋')}', 'bags', 'pcs', 1000, 25, 0.45)`,
    `  on conflict (business_id, sku) do nothing;`,
    `insert into pricing_policy (business_id, product_id, floor_price_usd, max_discount_pct, human_required_above_pct) values`,
    `  ('${B}', '${P}', 0.35, 10, 7) on conflict (business_id, product_id) do nothing;`,
    `insert into price_tiers (product_id, min_qty, unit_price_usd) values`,
    `  ('${P}', 1000, 0.50) on conflict (product_id, min_qty) do nothing;`,
    `insert into price_tiers (product_id, min_qty, unit_price_usd) values`,
    `  ('${P}', 5000, 0.45) on conflict (product_id, min_qty) do nothing;`,
    `insert into price_tiers (product_id, min_qty, unit_price_usd) values`,
    `  ('${P}', 20000, 0.38) on conflict (product_id, min_qty) do nothing;`,
    `insert into product_aliases (product_id, alias, language, alias_type) values`,
    `  ('${P}', 'shopping bag', 'en', 'common') on conflict do nothing;`,
    `insert into product_aliases (product_id, alias, language, alias_type) values`,
    `  ('${P}', 'non woven bag', 'en', 'common') on conflict do nothing;`,

    // Draft-first autonomy: every capability starts as a draft (the safe default).
    // The point of the sandbox is to practice the approval loop, so nothing auto-sends
    // until the owner deliberately promotes a capability.
    `insert into autonomy_policy (business_id, capability)`,
    `  select '${B}', c from (values ('greet'),('qualify'),('recommend'),('quote'),('negotiate'),('confirm_order'),('follow_up')) v(c)`,
    `  on conflict do nothing;`,
  ];
  return out.join('\n');
}
