import { DEMO_BUSINESS, DEMO_BUYERS, DEMO_NAMESPACE } from './factory.js';
import type { CapabilityEvidence } from '../core/trust/evidence.js';

/**
 * M5 — Deterministic trust history for 义乌宏发日用品厂. The demo employee is
 * deliberately NOT perfect: one promotion earned, one capability paused after
 * two corrections, one repaired mistake, one failed spot check. Supervised,
 * explainable, correctable, accountable — that is the pitch.
 *
 * Fixtures here feed the renderers, the tests, and demoTrustSeedSql().
 */

const B = DEMO_BUSINESS.id;
const sid = (n: number) => `de300000-0000-4000-8000-0000000004${String(n).padStart(2, '0')}`;

const DAY_MS = 24 * 3600 * 1000;
export const DEMO_NOW = new Date('2026-07-18T10:00:00Z');
const daysAgo = (d: number) => new Date(DEMO_NOW.getTime() - d * DAY_MS);

/** Promotion that happened: 接待问候, earned on countable evidence. */
export const DEMO_PROMOTED_EVIDENCE: CapabilityEvidence = {
  capability: 'greet', handled: 28, approvedNoEdit: 25, edited: 3,
  spotChecksPassed: 3, spotChecksFailed: 0, spotChecksSerious: 0,
  policyViolations: 0, hallucinationAttempts: 0,
  daysSupervised: 9, recentCorrections: 0, trainingExamples: 4,
};

/** Pause that happened: 报价 — two payment-term corrections in one week. */
export const DEMO_PAUSED_EVIDENCE: CapabilityEvidence = {
  capability: 'quote', handled: 14, approvedNoEdit: 11, edited: 3,
  spotChecksPassed: 1, spotChecksFailed: 1, spotChecksSerious: 0,
  policyViolations: 0, hallucinationAttempts: 0,
  daysSupervised: 9, recentCorrections: 2, trainingExamples: 5,
};

/*
 * M34.8 — DEMO_REPAIR and the `repairs` seed went with core/trust/repair.ts.
 * No surface reads that table: the repair protocol was modelled, never wired,
 * and the incident playbook now says so plainly. Seeding rows nothing renders
 * is how the demo factory hid the promotion defect for a year.
 */
export const DEMO_SPOT_CHECKS = [
  { id: sid(2), capability: 'greet', verdict: 'correct' as const, correction: null, daysAgo: 4 },
  { id: sid(3), capability: 'greet', verdict: 'correct' as const, correction: null, daysAgo: 2 },
  { id: sid(4), capability: 'quote', verdict: 'needs_improvement' as const,
    correction: '付款条件要写 TT 30% 定金，不能只写 TT', daysAgo: 3 },
];

/** Buyer-specific preference remembered (only for Ahmed). */
export const DEMO_BUYER_PREFERENCE = {
  buyer: DEMO_BUYERS[0]!,
  noteZh: '只发英文，不发语音；付款只走TT',
};

/** Single-quote escaping for the generated SQL literals. */
const esc = (s: string): string => s.replace(/'/g, "''");

export function demoTrustSeedSql(namespace: string = DEMO_NAMESPACE): string {
  const ev = (capability: string, action: string, fromMode: string, toMode: string,
    reasons: string, evidence: object, dAgo: number) =>
    `insert into capability_events (business_id, capability, action, from_mode, to_mode, reasons, evidence, actor, at)
select '${B}', '${capability}', '${action}', '${fromMode}', '${toMode}', array[${reasons}], '${esc(JSON.stringify(evidence))}'::jsonb, 'owner', now() - interval '${dAgo} days'
 where not exists (select 1 from capability_events where business_id = '${B}' and capability = '${capability}' and action = '${action}');`;

  const sql = [
    `-- M5 demo trust history (generated by src/demo/trust.ts)`,
    ev('greet', 'promote', 'draft', 'auto', `'evidence_met'`, DEMO_PROMOTED_EVIDENCE, 2),
    ev('quote', 'pause', 'auto', 'draft', `'repeated_corrections'`, DEMO_PAUSED_EVIDENCE, 1),
    `update autonomy_policy set mode = 'auto', time_window = null where business_id = '${B}' and capability = 'greet';`,
    `update autonomy_policy set mode = 'draft' where business_id = '${B}' and capability = 'quote';`,
    ...DEMO_SPOT_CHECKS.map((s) =>
      `insert into spot_checks (id, business_id, capability, verdict, correction, asked_at, answered_at)
values ('${s.id}', '${B}', '${s.capability}', '${s.verdict}', ${s.correction ? `'${esc(s.correction)}'` : 'null'}, now() - interval '${s.daysAgo} days', now() - interval '${s.daysAgo} days')
on conflict (id) do nothing;`),
    `update clients set notes = '${esc(DEMO_BUYER_PREFERENCE.noteZh)}' where id = '${DEMO_BUYER_PREFERENCE.buyer.id}' and (notes is null or notes = '');`,
  ].join('\n');
  // Same substitution as demoSeedSql: every id here derives from the namespace.
  return namespace === DEMO_NAMESPACE ? sql : sql.replaceAll(DEMO_NAMESPACE, namespace);
}
