import { DEMO_BUSINESS, DEMO_BUYERS } from './factory.js';
import type { CapabilityEvidence } from '../core/trust/evidence.js';
import type { RepairRecord } from '../core/trust/repair.js';
import type { ReviewStats } from '../core/trust/review.js';
import type { JourneyEvent } from '../core/trust/journey.js';

/**
 * M5 — Deterministic trust history for 义乌宏发日用品厂. The demo employee is
 * deliberately NOT perfect: one promotion earned, one capability paused after
 * two corrections, one repaired mistake, one failed spot check. Supervised,
 * explainable, correctable, accountable — that is the pitch.
 *
 * Fixtures here feed the renderers, the tests, and demoTrustSeedSql().
 */

const B = DEMO_BUSINESS.id;
const sid = (n: number) => `de300000-0000-4000-8000-0000000004${String(n).padStart(2, '0')}`;

const DAY_MS = 24 * 3600 * 1000;
export const DEMO_NOW = new Date('2026-07-18T10:00:00Z');
const daysAgo = (d: number) => new Date(DEMO_NOW.getTime() - d * DAY_MS);

/** Promotion that happened: 接待问候, earned on countable evidence. */
export const DEMO_PROMOTED_EVIDENCE: CapabilityEvidence = {
  capability: 'greet', handled: 28, approvedNoEdit: 25, edited: 3,
  spotChecksPassed: 3, spotChecksFailed: 0, spotChecksSerious: 0,
  policyViolations: 0, hallucinationAttempts: 0,
  daysSupervised: 9, recentCorrections: 0, trainingExamples: 4,
};

/** Pause that happened: 报价 — two payment-term corrections in one week. */
export const DEMO_PAUSED_EVIDENCE: CapabilityEvidence = {
  capability: 'quote', handled: 14, approvedNoEdit: 11, edited: 3,
  spotChecksPassed: 1, spotChecksFailed: 1, spotChecksSerious: 0,
  policyViolations: 0, hallucinationAttempts: 0,
  daysSupervised: 9, recentCorrections: 2, trainingExamples: 5,
};

/** The repaired mistake: wrong lead time reached Ahmed; corrected + learned. */
export const DEMO_REPAIR: RepairRecord = {
  id: sid(1), capability: 'quote',
  whatHappenedZh: '给 Ahmed 报的交期写成了15天，实际是20天',
  buyerReceivedMistake: true,
  containment: 'auto_replies_stopped',
  correctedDraft: 'Correction: lead time for ZX-200 is 20 days, not 15. Apologies for the confusion.',
  correctionApproved: true, correctionSent: true, correctionDelivered: true,
  learnedZh: '保温杯交期按产品表20天，不再手写',
  authorityChanged: false,
  verifiedAt: daysAgo(2),
  status: 'closed',
};

export const DEMO_SPOT_CHECKS = [
  { id: sid(2), capability: 'greet', verdict: 'correct' as const, correction: null, daysAgo: 4 },
  { id: sid(3), capability: 'greet', verdict: 'correct' as const, correction: null, daysAgo: 2 },
  { id: sid(4), capability: 'quote', verdict: 'needs_improvement' as const,
    correction: '付款条件要写 TT 30% 定金，不能只写 TT', daysAgo: 3 },
];

/** Buyer-specific preference remembered (only for Ahmed). */
export const DEMO_BUYER_PREFERENCE = {
  buyer: DEMO_BUYERS[0]!,
  noteZh: '只发英文，不发语音；付款只走TT',
};

export const DEMO_MONTH_STATS: ReviewStats = {
  conversations: 47, draftsApproved: 31, draftsEdited: 6, autoReplies: 22,
  buyerReplies: 38, quotes: 14, ordersProgressed: 2, nightShiftHandled: 9,
  escalations: 2, repairsOpened: 1, repairsClosed: 1,
  spotChecksPassed: 3, spotChecksFailed: 1, trainingExamplesAdded: 9,
  capabilitiesPromoted: ['接待问候'], capabilitiesLimited: [],
  previousEditRatio: 0.24,
};

/** First-week journey, as it actually unfolded for the demo factory. */
export const DEMO_JOURNEY: readonly JourneyEvent[] = [
  { beat: 'introduction', at: daysAgo(7) },
  { beat: 'first_correction', at: daysAgo(6) },
  { beat: 'first_night_shift', at: daysAgo(5) },
  { beat: 'first_spot_check', at: daysAgo(4) },
  { beat: 'buyer_memory', at: daysAgo(3) },
  { beat: 'progress_update', at: daysAgo(2) },
  { beat: 'weekly_summary', at: daysAgo(1) },
];

const esc = (s: string): string => s.replace(/'/g, "''");

/** Idempotent: identity-PK tables guard with not-exists; uuid tables on-conflict. */
export function demoTrustSeedSql(): string {
  const ev = (capability: string, action: string, fromMode: string, toMode: string,
    reasons: string, evidence: object, dAgo: number) =>
    `insert into capability_events (business_id, capability, action, from_mode, to_mode, reasons, evidence, actor, at)
select '${B}', '${capability}', '${action}', '${fromMode}', '${toMode}', array[${reasons}], '${esc(JSON.stringify(evidence))}'::jsonb, 'owner', now() - interval '${dAgo} days'
 where not exists (select 1 from capability_events where business_id = '${B}' and capability = '${capability}' and action = '${action}');`;

  return [
    `-- M5 demo trust history (generated by src/demo/trust.ts)`,
    ev('greet', 'promote', 'draft', 'auto', `'evidence_met'`, DEMO_PROMOTED_EVIDENCE, 2),
    ev('quote', 'pause', 'auto', 'draft', `'repeated_corrections'`, DEMO_PAUSED_EVIDENCE, 1),
    `update autonomy_policy set mode = 'auto', time_window = null where business_id = '${B}' and capability = 'greet';`,
    `update autonomy_policy set mode = 'draft' where business_id = '${B}' and capability = 'quote';`,
    ...DEMO_SPOT_CHECKS.map((s) =>
      `insert into spot_checks (id, business_id, capability, verdict, correction, asked_at, answered_at)
values ('${s.id}', '${B}', '${s.capability}', '${s.verdict}', ${s.correction ? `'${esc(s.correction)}'` : 'null'}, now() - interval '${s.daysAgo} days', now() - interval '${s.daysAgo} days')
on conflict (id) do nothing;`),
    `insert into repairs (id, business_id, capability, record, status, opened_at, closed_at)
values ('${DEMO_REPAIR.id}', '${B}', 'quote', '${esc(JSON.stringify(DEMO_REPAIR))}'::jsonb, 'closed', now() - interval '3 days', now() - interval '2 days')
on conflict (id) do nothing;`,
    `update clients set notes = '${esc(DEMO_BUYER_PREFERENCE.noteZh)}' where id = '${DEMO_BUYER_PREFERENCE.buyer.id}' and (notes is null or notes = '');`,
  ].join('\n');
}
